import { useEffect, useState } from 'react';
import { Bell, ChevronRight, LoaderCircle, Search } from 'lucide-react';
import { api, seriesLabel, type Drama, type User } from './api';
import { Modal } from './Modal';

export function Following({user,onLogin,onView,refresh,onChange}:{user:User|null;onLogin:()=>void;onView:(id:number)=>void;refresh:number;onChange:()=>void}) {
  const [rows,setRows]=useState<Drama[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[removing,setRemoving]=useState<Drama|null>(null),[busy,setBusy]=useState(false),[removeError,setRemoveError]=useState('');
  useEffect(()=>{if(!user){setLoading(false);return;}let active=true;setLoading(true);setError('');api<Drama[]>('/me/following').then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id,refresh,retry]);
  async function remove(){if(!removing||busy)return;setBusy(true);setRemoveError('');try{await api('/dramas/'+removing.id+'/follow',{method:'DELETE'});setRows(r=>r.filter(d=>d.id!==removing.id));setRemoving(null);onChange();}catch(e){setRemoveError((e as Error).message);}finally{setBusy(false);}}
  const visible=rows.filter(d=>d.title.includes(query.trim())&&(filter==='all'||filter==='new'&&(d.newEpisodes||0)>0||filter===d.seriesStatus));
  return <section className="following-page"><div className="page-intro"><div><p className="eyebrow">让喜欢的故事，有下文</p><h1>我的追剧</h1><p className="following-subtitle">连载更新、未看新集，都在这里。</p></div><Bell className="following-icon" size={30}/></div>
    {!user?<div className="empty"><Bell size={34}/><h3>登录后开始追剧</h3><p>在播放页点“追剧”，随时回来接着看。</p><button className="primary" onClick={onLogin}>登录 / 注册</button></div>:<>
    <div className="following-tools"><div className="categories">{[['all','全部'],['new','有新集'],['SERIALIZING','连载中'],['COMPLETED','已完结']].map(([value,label])=><button key={value} className={filter===value?'category selected':'category'} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="search-box"><Search size={16}/><input aria-label="搜索追剧" placeholder="搜索正在追的短剧" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
    {loading?<div className="empty"><LoaderCircle className="spin"/>加载追剧片单…</div>:error?<div className="empty"><p>{error}</p><button className="secondary" onClick={()=>setRetry(n=>n+1)}>重试</button></div>:!visible.length?<div className="empty"><Bell size={30}/><h3>{rows.length?'没有符合条件的短剧':'追剧片单还是空的'}</h3><p>{rows.length?'试试其他筛选，或清空搜索。':'在播放页点“追剧”，这里就能显示最新集数。'}</p></div>:<div className="following-list">{visible.map(d=><article className="following-card" key={d.id}><button className="following-cover" aria-label={'观看'+d.title} onClick={()=>onView(d.id)}><img src={d.coverImg} alt={d.title+'封面'}/>{(d.newEpisodes||0)>0&&<span>有新集</span>}</button><div className="following-content"><span className="small-tag">{d.category}</span><h2>{d.title}</h2><p>{seriesLabel(d)}</p><p className="following-progress">{d.newEpisodes?d.newEpisodes+' 集新上线 · ':''}{d.remainingEpisodes?d.remainingEpisodes+' 集还没看完':'已追到最新进度'}</p><div><button className="primary" onClick={()=>onView(d.id)}>继续观看<ChevronRight size={15}/></button><button className="following-remove" onClick={()=>{setRemoving(d);setRemoveError('');}}>取消追剧</button></div></div></article>)}</div>}
    </>}
    {removing&&<Modal label="取消追剧" onClose={()=>{if(!busy)setRemoving(null);}}><h2>取消追剧「{removing.title}」？</h2><p className="muted">收藏和观看进度会保留。</p>{removeError&&<p className="form-error" role="alert">{removeError}</p>}<div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setRemoving(null)}>继续追剧</button><button className="primary destructive" disabled={busy} onClick={remove}>确认取消追剧</button></div></Modal>}
  </section>;
}
