CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(24) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(30) NOT NULL,
  role VARCHAR(10) NOT NULL DEFAULT 'USER',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_username UNIQUE (username),
  CONSTRAINT ck_user_role CHECK (role IN ('USER','ADMIN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_profile (
  user_id BIGINT PRIMARY KEY,
  avatar_url VARCHAR(255),
  background_url VARCHAR(255),
  CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS drama (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(80) NOT NULL,
  cover_img VARCHAR(1000) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  video_url VARCHAR(1000) NOT NULL,
  category VARCHAR(20) NOT NULL DEFAULT '都市',
  view_count BIGINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_drama_category (category),
  CONSTRAINT ck_drama_views CHECK (view_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_favorite (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_favorite UNIQUE (user_id,drama_id),
  CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_favorite_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_like (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_like UNIQUE (user_id,drama_id),
  CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_like_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS watch_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  progress_sec INT NOT NULL DEFAULT 0,
  duration_sec INT NOT NULL DEFAULT 0,
  last_watched TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uk_watch_history UNIQUE (user_id,drama_id),
  CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_history_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE,
  CONSTRAINT ck_history_progress CHECK (progress_sec >= 0 AND duration_sec >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS drama_comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  content VARCHAR(500) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_comment_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE,
  INDEX idx_comment_drama_time (drama_id,create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS drama_series (
  drama_id BIGINT PRIMARY KEY,
  status VARCHAR(12) NOT NULL DEFAULT 'COMPLETED',
  total_episodes INT NOT NULL DEFAULT 1,
  CONSTRAINT fk_series_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE,
  CONSTRAINT ck_series_status CHECK (status IN ('SERIALIZING','COMPLETED')),
  CONSTRAINT ck_series_total CHECK (total_episodes BETWEEN 1 AND 500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS drama_episode (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drama_id BIGINT NOT NULL,
  episode_no INT NOT NULL,
  title VARCHAR(80) NOT NULL,
  video_url VARCHAR(1000) NOT NULL,
  create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uk_episode_number UNIQUE (drama_id,episode_no),
  CONSTRAINT fk_episode_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE,
  CONSTRAINT ck_episode_number CHECK (episode_no BETWEEN 1 AND 500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS episode_progress (
  user_id BIGINT NOT NULL,
  episode_id BIGINT NOT NULL,
  progress_sec INT NOT NULL DEFAULT 0,
  duration_sec INT NOT NULL DEFAULT 0,
  last_watched TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id,episode_id),
  CONSTRAINT fk_episode_progress_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_episode_progress_episode FOREIGN KEY (episode_id) REFERENCES drama_episode(id) ON DELETE CASCADE,
  CONSTRAINT ck_episode_progress CHECK (progress_sec >= 0 AND duration_sec >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_follow (
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id,drama_id),
  CONSTRAINT fk_follow_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_follow_drama FOREIGN KEY (drama_id) REFERENCES drama(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
